const LIGHT_STATE = "LIGHT_STATE";
const BREATHE_LIGHT_EFFECT = "BREATHE_LIGHT_EFFECT";
const PULSE_LIGHT_EFFECT = "PULSE_LIGHT_EFFECT";
const ON = "ON";
const ENERGY = "ENERGY";
const CONTACT = "CONTACT";
const TEMPERATURE = "TEMPERATURE";
const HUMIDITY = "HUMIDITY";
const LIGHT = "LIGHT";
const UV = "UV";
const VIBRATION = "VIBRATION";
const BATTERY_LEVEL = "BATTERY_LEVEL";
const MOTION = "MOTION";
const AUDIO_PLAYING_STATE = "AUDIO_PLAYING_STATE";
const PREVIOUS_AUDIO_TRACK = "PREVIOUS_AUDIO_TRACK";
const NEXT_AUDIO_TRACK = "NEXT_AUDIO_TRACK";
const MUTED_AUDIO = "MUTED_AUDIO";
const QUEUE_FLUSHED = "QUEUE_FLUSHED";
const VOLUME = "VOLUME";
const SEEK = "SEEK";
const NAME = "NAME";
const LED_STATE = "LED_STATE";
const CURRENT_AUDIO_TRACK = "CURRENT_AUDIO_TRACK";
const ADDED_TO_QUEUE_NEXT = "ADDED_TO_QUEUE_NEXT";
const ADDED_TO_QUEUE_BOTTOM = "ADDED_TO_QUEUE_BOTTOM";
const TAMPER = "TAMPER";
const BUTTON = "BUTTON";

module.exports = {
  DEVICE_EVENT: "DEVICE:EVENT",
  DEVICE_LIGHT_EVENT: "DEVICE_LIGHT:EVENT",
  DEVICE_SENSOR_EVENT: "DEVICE_SENSOR:EVENT",
  DEVICE_SOCKET_EVENT: "DEVICE_SOCKET:EVENT",
  DEVICE_SPEAKER_EVENT: "DEVICE_SPEAKER:EVENT",
  DEVICE_DOORBELL_EVENT: "DEVICE_DOORBELL:EVENT",
  events: {
    LIGHT_STATE,
    BREATHE_LIGHT_EFFECT,
    PULSE_LIGHT_EFFECT,
    ON,
    ENERGY,
    CONTACT,
    TEMPERATURE,
    HUMIDITY,
    LIGHT,
    UV,
    VIBRATION,
    BATTERY_LEVEL,
    MOTION,
    AUDIO_PLAYING_STATE,
    PREVIOUS_AUDIO_TRACK,
    NEXT_AUDIO_TRACK,
    MUTED_AUDIO,
    QUEUE_FLUSHED,
    VOLUME,
    SEEK,
    NAME,
    LED_STATE,
    CURRENT_AUDIO_TRACK,
    ADDED_TO_QUEUE_NEXT,
    ADDED_TO_QUEUE_BOTTOM,
    TAMPER,
    BUTTON
  }
};
